linters:
  enable-all: true
  disable:
    - wrapcheck # TODO fix
    - err113 # TODO fix
    - testifylint # TODO fix
    - varnamelen
    - testpackage
    - nonamedreturns
    - nlreturn
    - ireturn
    - mnd
    - gomnd
    - exhaustruct
    - goconst
    - godox
    - depguard
    - wsl
    - lll
    - cyclop
    - gocognit
    - gocyclo
    - maintidx
    - execinquery
    - gochecknoglobals

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - forcetypeassert