name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: GoReleaser
    steps:
      - uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - name: Run go mod download
        run: go mod download
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: curl -sL https://git.io/goreleaser | bash